services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HTTP Event Collector
      - "9997:9997"   # Forwarder port
    environment:
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=MySecurePassword123   # Change this to something strong
    volumes:
      - splunk-data:/opt/splunk/var
    restart: unless-stopped

volumes:
  splunk-data:

